version: "3.3"

services:

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
      target: dev
    container_name: api
    restart: always
    ports:
      - "8081:8081"
      - "8080:8082"
    volumes:
      - ./api/scripts:/api/scripts
      - ./api/api.jl:/api/api.jl
      - ./api/logs:/api/logs
      - ./api/input_files:/api/input_files
      - ./api/results:/api/results
    # command: julia --project=. -e 'include("api.jl")' --color=yes --depwarn=no --project=@. --sysimage="pre-compilation/sysimage.so" -q -i -- $$(dirname $$0)/../bootstrap.jl -s=true "$$@"

    command: julia --project=. -e 'include("api.jl")'


  gui:
    build: ./gui
    container_name: gui
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ./gui:/app

    command: streamlit run app.py --global.disableWidgetStateDuplicationWarning true --server.port=8501