services:
  api:
    image: ghcr.io/battmoteam/battmo_api:latest
    container_name: api
    restart: always
    ports:
      - "8081:8081"
      - "8080:8080"
    networks:
      - app-network
    command: julia --project=. -e 'include("api.jl")' --color=yes --depwarn=no --project=@. --sysimage="pre-compilation/sysimage.so" -q -i -- $$(dirname $$0)/../bootstrap.jl -s=true "$$@"

  gui:
    build: ./nextjs
    container_name: nextjs
    restart: always
    ports:
      - "3001:3000"
    networks:
      - app-network
    # Only mount source code, not node_modules
    volumes:
      - ./nextjs/app:/app/app
      - ./nextjs/components:/app/components
      - /app/node_modules
    command: npm run dev -- -H 0.0.0.0

networks:
  app-network:
    driver: bridge