version: "3.3"

services:

  api:
    image: ghcr.io/battmoteam/battmo_api:latest
    container_name: api
    restart: always
    ports:
      - "8081:8081"
      - "8080:8080"
    networks:
      - app-network  

    command: julia --project=. -e 'include("api.jl")' --color=yes --depwarn=no --project=@. --sysimage="pre-compilation/sysimage.so" -q -i -- $$(dirname $$0)/../bootstrap.jl -s=true "$$@"


  nginx:
    image: ghcr.io/battmoteam/battmoapp_nginx:latest
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /usr/share/nginx/html/.well-known:/usr/share/nginx/html/.well-known
    command: nginx -g 'daemon off;'

  certbot:
    image: certbot/certbot
    container_name: certbot
    networks:
      - app-network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /usr/share/nginx/html/.well-known:/usr/share/nginx/html/.well-known
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /usr/share/nginx/html --quiet; sleep 12h; done"

  gui:
    image: ghcr.io/battmoteam/battmoapp_gui:latest
    build: ./gui
    container_name: gui
    restart: always
    ports:
      - "8501:8501"
    networks:
      - app-network
    command: streamlit run app.py --global.disableWidgetStateDuplicationWarning true --server.port=8501


networks:
  app-network:
    driver: bridge