version: "3.3"

services:

  api:
    image: ghcr.io/battmoteam/battmoapp_api:latest
    build:
      context: ./api
      dockerfile: Dockerfile
      target: prod
    container_name: api
    restart: always
    ports:
      - "8081:8081"
      - "8080:8080"
    command: julia --project=. -e 'include("api.jl")' --color=yes --depwarn=no --project=@. --sysimage="pre-compilation/sysimage.so" -q -i -- $$(dirname $$0)/../bootstrap.jl -s=true "$$@"

  nginx:
    image: ghcr.io/battmoteam/battmoapp_nginx:latest
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - api
      - gui
    volumes:
      - /etc/letsencrypt/live/app.batterymodel.com:/etc/letsencrypt/live/app.batterymodel.com:ro
    command: /bin/bash -c "/renew-certs.sh && nginx -g 'daemon off;'"


 
  gui:
    image: ghcr.io/battmoteam/battmoapp_gui:latest
    build: ./gui
    container_name: gui
    restart: always
    ports:
      - "8501:8501"
    command: streamlit run app.py --global.disableWidgetStateDuplicationWarning true --server.port=8501
