version: "3.3"

services:
  api:
    image: ghcr.io/battmoteam/battmo_api:latest
    container_name: api
    restart: always
    ports:
      - "8081:8081"
      - "8080:8080"
    networks:
      - app-network
    command: julia --project=. -e 'include("api.jl")' --color=yes --depwarn=no --project=@. --sysimage="pre-compilation/sysimage.so" -q -i -- $$(dirname $$0)/../bootstrap.jl -s=true "$$@"

  gui:
    build: ./gui
    container_name: gui
    restart: always
    ports:
      - "8501:8501"
    networks:
      - app-network
    volumes:
      - ./gui:/app

    command: python main.py

networks:
  app-network:
    driver: bridge
