services:
  api:
    build: 
      context: ./battmo-api
      dockerfile: Dockerfile
      target: dev
    container_name: api
    restart: always
    ports:
      - "8081:8081"
      - "8080:8082"
    volumes:
      - ./battmo-api/scripts:/api/scripts
      - ./battmo-api/api.jl:/api/api.jl
      - ./battmo-api/logs:/api/logs
      - ./battmo-api/input_files:/api/input_files
      - ./battmo-api/results:/api/results
    networks:
      - app-network
    command: julia --project=. -e 'include("api.jl")'

  gui:
    build: ./nextjs-gui
    container_name: gui
    restart: always
    ports:
      - "3001:3000"
    networks:
      - app-network
    volumes:
      - ./nextjs-gui/app:/app/app
      - ./nextjs-gui/components:/app/components
    command: npm run dev -- -H 0.0.0.0

networks:
  app-network:
    driver: bridge